print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? \n$"))
tip = int(input("What percentage tip would you like to give?\n 10 12 15 20 \n"))
people = int(input("How many people to split the bill?\n "))
pay = round(((bill + bill*tip/100) / people), 2)
print(f"Each Persons Should To Pay = {pay} $")
